[db_config]
USER="avinyaDBAdmin"
PASSWORD="Polkatu!23"
HOST="avinyafoundation-db-server.mysql.database.azure.com"
PORT=3306
DATABASE="sms_db"

[endpoint_ports]
sms_endpoint=9090
hrm_endpoint=9091
acadamic_endpoint=9092
inventory_endpoint=9093